'use client';

import React, { useState } from 'react';
import { X, MessageSquareText, Copy, Check, Printer, BookOpen, Search, RefreshCw, History } from 'lucide-react';
import { useAssistant } from './AssistantContext';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

export function AssistantModals() {
  const {
    result, trade, currentProject, query,
    showNoticeModal, setShowNoticeModal,
    showPrintModal, setShowPrintModal,
    showCodebookModal, setShowCodebookModal,
    showHistoryDrawer, setShowHistoryDrawer,
    docSearchQuery, setDocSearchQuery,
    indexedDocs, loadingDocs,
    queryHistory, setQueryHistory, setQuery, setTrade, setJurisdiction,
    completedActions, jurisdiction, docType
  } = useAssistant();

  const [copiedNotice, setCopiedNotice] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);

  const getVerdictDetails = (verdict: string) => {
    switch (verdict) {
      case 'Compliant': return { badgeText: 'APPROVED • CODE COMPLIANT' };
      case 'Non-Compliant': return { badgeText: 'PROHIBITED • CODE VIOLATION' };
      default: return { badgeText: 'ADDITIONAL INFORMATION REQUIRED' };
    }
  };

  const copyToClipboard = (text: string, type: 'notice' | 'report') => {
    navigator.clipboard.writeText(text);
    if (type === 'notice') {
      setCopiedNotice(true);
      setTimeout(() => setCopiedNotice(false), 2000);
    } else {
      setCopiedReport(true);
      setTimeout(() => setCopiedReport(false), 2000);
    }
  };

  const generateSubcontractorNotice = () => {
    if (!result) return '';
    const verdictInfo = getVerdictDetails(result.verdict);
    const primaryCite = result.citations?.[0];
    return `ATTN: ${trade === 'All' ? 'Trade' : trade} Subcontractor Foreman
PROJECT: ${currentProject.name}
DATE: ${new Date().toLocaleDateString()}
STATUS: ${verdictInfo.badgeText}

OBSERVATION / ITEM:
"${query}"

COMPLIANCE SUMMARY:
${result.summary}

${primaryCite ? `GOVERNING CODE SECTION:
${primaryCite.clause_number} (${primaryCite.document_title})
"${primaryCite.direct_quote}"` : ''}

REQUIRED REMEDIATION / ACTION ITEMS:
${result.recommended_actions?.map((a: string, i: number) => `${i + 1}. ${a}`).join('\n')}

Please review and confirm remediation before calling for scheduled field inspection.`;
  };

  const formatReportMarkdown = () => {
    if (!result) return '';
    const verdictInfo = getVerdictDetails(result.verdict);
    return `# JOBSITE COMPLIANCE & SAFETY INSPECTION REPORT
Generated by SiteCode AI Building Code Advisor
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Project: ${currentProject.name} (${currentProject.phase})
Location: ${currentProject.location}
Date & Time: ${new Date().toLocaleString()}
Inspection Scope: Trade: ${trade} | Jurisdiction: ${jurisdiction} | Document Scope: ${docType}

INSPECTION QUESTION / OBSERVATION:
"${query}"

COMPLIANCE DETERMINATION:
Status: ${verdictInfo.badgeText}
Confidence Match: ${(result.confidence_score * 100).toFixed(0)}%

EXECUTIVE SUMMARY:
${result.summary}

OFFICIAL CODE REFERENCES & CITATIONS:
${result.citations
  ?.map(
    (c: any, i: number) => `${i + 1}. [${c.clause_number}] ${c.document_title} (${c.page_or_section})
   Quote: "${c.direct_quote}"
   Application: ${c.relevance_explanation}`
  )
  .join('\n\n')}

REQUIRED JOBSITE ACTIONS & CHECKLIST:
${result.recommended_actions?.map((a: string, i: number) => `[ ${completedActions[i] ? 'X' : ' '} ] ${a}`).join('\n')}

TECHNICAL GUIDANCE:
${result.technical_analysis}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report Verified via Official Building Code Library
`;
  };

  const filteredDocs = indexedDocs.filter(d => {
    if (!docSearchQuery.trim()) return true;
    const q = docSearchQuery.toLowerCase();
    return (
      d.clause_number?.toLowerCase().includes(q) ||
      d.title?.toLowerCase().includes(q) ||
      d.trade?.toLowerCase().includes(q) ||
      d.summary_snippet?.toLowerCase().includes(q)
    );
  });

  return (
    <>
      {/* Subcontractor Field Notice */}
      {showNoticeModal && result && (
        <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4">
          <Card className="max-w-xl w-full p-6 shadow-2xl space-y-4 animate-in zoom-in-95">
            <div className="flex items-center justify-between border-b pb-3">
              <div className="flex items-center gap-2">
                <MessageSquareText className="w-5 h-5 text-primary" />
                <h3 className="font-bold text-base">Field Notice for Trade Subcontractor</h3>
              </div>
              <Button variant="ghost" size="icon" onClick={() => setShowNoticeModal(false)}>
                <X className="w-4 h-4" />
              </Button>
            </div>
            <p className="text-sm text-muted-foreground">
              Copy and send this pre-formatted notice directly via Email, SMS, or Procore to your subcontractor foreman:
            </p>
            <textarea
              readOnly
              rows={12}
              value={generateSubcontractorNotice()}
              className="w-full bg-muted border rounded-xl p-3.5 text-sm font-mono leading-relaxed focus:outline-none"
            />
            <div className="flex items-center justify-between pt-2">
              <span className="text-[11px] text-muted-foreground">Ready to paste into communication apps</span>
              <Button onClick={() => copyToClipboard(generateSubcontractorNotice(), 'notice')} className="gap-1.5 font-bold">
                {copiedNotice ? <><Check className="w-4 h-4" /><span>Copied!</span></> : <><Copy className="w-4 h-4" /><span>Copy Notice Text</span></>}
              </Button>
            </div>
          </Card>
        </div>
      )}

      {/* Printable Official Report */}
      {showPrintModal && result && (
        <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4">
          <Card className="max-w-2xl w-full p-6 shadow-2xl space-y-4 max-h-[90vh] overflow-y-auto animate-in zoom-in-95">
            <div className="flex items-center justify-between border-b pb-3">
              <div className="flex items-center gap-2">
                <Printer className="w-5 h-5 text-primary" />
                <h3 className="font-bold text-base">Official Jobsite Inspection Report</h3>
              </div>
              <Button variant="ghost" size="icon" onClick={() => setShowPrintModal(false)}>
                <X className="w-4 h-4" />
              </Button>
            </div>
            <div className="bg-muted p-4 rounded-xl border text-sm font-mono whitespace-pre-wrap leading-relaxed select-all">
              {formatReportMarkdown()}
            </div>
            <div className="flex items-center justify-between pt-2">
              <Button variant="outline" onClick={() => copyToClipboard(formatReportMarkdown(), 'report')} className="gap-1.5">
                {copiedReport ? <><Check className="w-4 h-4 text-emerald-500" /><span>Copied!</span></> : <><Copy className="w-4 h-4" /><span>Copy Markdown</span></>}
              </Button>
              <Button onClick={() => window.print()} className="gap-2 font-bold">
                <Printer className="w-4 h-4" /><span>Print Document</span>
              </Button>
            </div>
          </Card>
        </div>
      )}

      {/* Codebook Library Explorer */}
      {showCodebookModal && (
        <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4">
          <Card className="max-w-3xl w-full p-6 shadow-2xl space-y-4 max-h-[85vh] flex flex-col animate-in zoom-in-95">
            <div className="flex items-center justify-between border-b pb-3">
              <div className="flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-sky-500" />
                <div>
                  <h3 className="font-bold text-base">Building Codebook & Specification Library</h3>
                  <p className="text-[11px] text-muted-foreground">Search official indexed statutory building codes & standard divisions</p>
                </div>
              </div>
              <Button variant="ghost" size="icon" onClick={() => setShowCodebookModal(false)}>
                <X className="w-4 h-4" />
              </Button>
            </div>
            <div className="relative">
              <Search className="w-4 h-4 text-muted-foreground absolute left-3.5 top-3" />
              <input
                type="text"
                value={docSearchQuery}
                onChange={(e) => setDocSearchQuery(e.target.value)}
                placeholder="Search by code section (e.g., 'NEC 300.22', 'IBC 714')..."
                className="w-full bg-background border rounded-xl pl-10 pr-4 py-2 text-sm focus:outline-none focus:border-primary"
              />
            </div>
            <div className="flex-1 overflow-y-auto space-y-3 pr-1">
              {loadingDocs ? (
                <div className="py-12 text-center text-sm text-muted-foreground flex items-center justify-center gap-2">
                  <RefreshCw className="w-4 h-4 animate-spin text-primary" />
                  <span>Loading official code database...</span>
                </div>
              ) : filteredDocs.length > 0 ? (
                filteredDocs.map((doc: any) => (
                  <Card key={doc.id} className="p-3.5 space-y-1.5 hover:border-primary/50 transition-all">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-bold text-primary font-mono">{doc.clause_number}</span>
                      <span className="text-[10px] px-2 py-0.5 rounded bg-muted text-muted-foreground font-semibold">{doc.trade} • {doc.jurisdiction}</span>
                    </div>
                    <h4 className="text-sm font-bold">{doc.title}</h4>
                    <p className="text-sm line-clamp-2 bg-muted/50 p-2 rounded-lg border">{doc.summary_snippet}</p>
                    <div className="text-[10px] text-muted-foreground flex justify-between pt-0.5">
                      <span>{doc.document_type}</span>
                      <span>Section: {doc.page_or_section}</span>
                    </div>
                  </Card>
                ))
              ) : (
                <div className="py-8 text-center text-sm text-muted-foreground">No matching code clauses found in the database.</div>
              )}
            </div>
            <div className="flex justify-end pt-2 border-t">
              <Button variant="outline" onClick={() => setShowCodebookModal(false)}>Close Library</Button>
            </div>
          </Card>
        </div>
      )}

      {/* History Drawer */}
      {showHistoryDrawer && (
        <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex justify-end">
          <Card className="w-full max-w-md h-full p-6 shadow-2xl flex flex-col space-y-4 rounded-none animate-in slide-in-from-right duration-200">
            <div className="flex items-center justify-between border-b pb-3">
              <div className="flex items-center gap-2">
                <History className="w-5 h-5 text-primary" />
                <h3 className="font-bold text-base">Inspection Session History</h3>
              </div>
              <Button variant="ghost" size="icon" onClick={() => setShowHistoryDrawer(false)}>
                <X className="w-4 h-4" />
              </Button>
            </div>
            <div className="flex-1 overflow-y-auto space-y-2.5">
              {queryHistory.map((item: any) => (
                <button
                  key={item.id}
                  type="button"
                  onClick={() => {
                    setQuery(item.query);
                    setTrade(item.trade);
                    setJurisdiction(item.jurisdiction);
                    setShowHistoryDrawer(false);
                    window.scrollTo({ top: 0, behavior: 'smooth' });
                  }}
                  className="w-full text-left p-3.5 border rounded-xl hover:border-primary/50 space-y-1.5 transition-all bg-card"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] text-muted-foreground">{item.timestamp}</span>
                    <span className={`text-[9px] px-2 py-0.5 rounded-full font-bold ${
                      item.verdict === 'Compliant' ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400' :
                      item.verdict === 'Non-Compliant' ? 'bg-rose-500/20 text-rose-600 dark:text-rose-400' :
                      'bg-amber-500/20 text-amber-600 dark:text-amber-400'
                    }`}>
                      {item.verdict}
                    </span>
                  </div>
                  <p className="text-sm font-medium line-clamp-2">{item.query}</p>
                  <div className="text-[10px] text-primary">Trade: {item.trade}</div>
                </button>
              ))}
            </div>
            <div className="pt-2 border-t flex justify-between">
              <Button variant="ghost" className="text-destructive hover:text-destructive hover:bg-destructive/10" onClick={() => { setQueryHistory([]); setShowHistoryDrawer(false); }}>
                Clear History
              </Button>
              <Button variant="outline" onClick={() => setShowHistoryDrawer(false)}>Close</Button>
            </div>
          </Card>
        </div>
      )}
    </>
  );
}
